### ISSUE TITLE
MongoDB : "Monitor thread successfully connected" spammed indefinitely

### ISSUE THREAD

**Issue by Pakho** [vert-x3/vertx-mongo-client#231] opened 2020-07-04 19:11 UTC
### Questions

I am using es4x in Linux, with vertx on GraalVM to deploy a server and connect to MongoDB. 

The connection is successful, but I get this message in the terminal at about every 10 seconds (but sometimes it would skip a beat). 

`Monitor thread successfully connected to server with description ServerDescription{address=Myproject-shard-00-02.ezaez.mongodb.net:27017, type=REPLICA_SET_SECONDARY, state=CONNECTED, ok=true, version=ServerVersion{versionList=[4, 2, 8]}, minWireVersion=0, maxWireVersion=8, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=34203441, setName='atlas-3kttsy-shard-0', canonicalAddress=Myproject-shard-00-02.ezaez.mongodb.net:27017, hosts=[Myproject-shard-00-00.ezaez.mongodb.net:27017, Myproject-shard-00-01.ezaez.mongodb.net:27017, Myproject-shard-00-02.ezaez.mongodb.net:27017], passives=[], arbiters=[], primary='Myproject-shard-00-01.ezaez.mongodb.net:27017', tagSet=TagSet{[Tag{name='region', value='US_EAST_1'}, Tag{name='nodeType', value='ELECTABLE'}, Tag{name='provider', value='AWS'}]}, electionId=null, setVersion=3, lastWriteDate=Sat Jul 04 14:42:08 EDT 2020, lastUpdateTimeNanos=3177399557511}
`

### Version

Vertx 3.9.1
Graalvm-ce-java11-linux-amd64-20.1.0

### Context

Here is the code for the successful connection to MongoDB:

```
`import { MongoClient } from "@vertx/mongo-client"


const config = {
    "connection_string" : "mongodb://usernamehidden:passwordhidden@Myproject-shard-00-02.ezaez.mongodb.net:27017/test?authSource=admin&ssl=true"
}

let client = MongoClient.create(vertx, config);`
```

As you can see after running npm start, it connects successfully but get this messages spammed every 10 seconds (it skips a beat or two sometimes):

`Succeeded in deploying verticle
Opened connection [connectionId{localValue:1, serverValue:252329}] to Myproject-shard-00-02.ezaez.mongodb.net:27017`

`Monitor thread successfully connected to server with description ServerDescription{address=Myproject-shard-00-02.ezaez.mongodb.net:27017, type=REPLICA_SET_SECONDARY, state=CONNECTED, ok=true, version=ServerVersion{versionList=[4, 2, 8]}, minWireVersion=0, maxWireVersion=8, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=34203441, setName='atlas-3kttsy-shard-0', canonicalAddress=Myproject-shard-00-02.ezaez.mongodb.net:27017, hosts=[Myproject-shard-00-00.ezaez.mongodb.net:27017, Myproject-shard-00-01.ezaez.mongodb.net:27017, Myproject-shard-00-02.ezaez.mongodb.net:27017], passives=[], arbiters=[], primary='Myproject-shard-00-01.ezaez.mongodb.net:27017', tagSet=TagSet{[Tag{name='region', value='US_EAST_1'}, Tag{name='nodeType', value='ELECTABLE'}, Tag{name='provider', value='AWS'}]}, electionId=null, setVersion=3, lastWriteDate=Sat Jul 04 14:42:08 EDT 2020, lastUpdateTimeNanos=3177399557511}`

10 seconds after .. 

`Monitor thread successfully connected to server with description ServerDescription{address=Myproject-shard-00-02.ezaez.mongodb.net:27017, type=REPLICA_SET_SECONDARY, state=CONNECTED, ok=true, version=ServerVersion{versionList=[4, 2, 8]}, minWireVersion=0, maxWireVersion=8, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=33787403, setName='atlas-3kttsy-shard-0', canonicalAddress=Myproject-shard-00-02.ezaez.mongodb.net:27017, hosts=[Myproject-shard-00-00.ezaez.mongodb.net:27017, Myproject-shard-00-01.ezaez.mongodb.net:27017, Myproject-shard-00-02.ezaez.mongodb.net:27017], passives=[], arbiters=[], primary='Myproject-shard-00-01.ezaez.mongodb.net:27017', tagSet=TagSet{[Tag{name='nodeType', value='ELECTABLE'}, Tag{name='provider', value='AWS'}, Tag{name='region', value='US_EAST_1'}]}, electionId=null, setVersion=3, lastWriteDate=Sat Jul 04 14:42:18 EDT 2020, lastUpdateTimeNanos=3187457595442}`

and so on. Notice the timestamps lastWriteDate.

### Steps to reproduce

Install es4x with GraalVM. Use MongoDB-Client library of Vertx to do a connection with a Mongo cloud cluster.

**Comment by pmlopes** [comment] 2020-07-06 09:44
In es4x to reduce the configuration by the end user, we ship the following logger settings:

https://github.com/reactiverse/es4x/blob/develop/es4x/src/main/resources/vertx-default-jul-logging.properties

Perhaps we should reduce the default level `.level` to warning instead of info.

If you add this file to your project root with `WARNING` instead it may hide the message.

**Comment by Pakho** [comment] 2020-07-06 22:27
Thanks for the input. Unfortunately it is not working, the problem persist. It makes developing almost impossible. 

Not only I have added the file to the project root (same folder as my index.js), but I also changed the property file under graalVM/conf  to WARNING.

**Comment by pmlopes** [comment] 2020-07-07 11:25
@Pakho from what I can see the message is comming from `com.mongodb.internal.connection.DefaultServerMonitor` which is using `SLF4J` as a logger.

The logger name is: `org.mongodb.driver.cluster` as described here: http://mongodb.github.io/mongo-java-driver/3.0/driver/reference/management/logging/

Now this means that SLF4J is on the classpath otherwise this code on the driver would not do anything:

```java
    private static boolean shouldUseSLF4J() {
        try {
            Class.forName("org.slf4j.Logger");
            return true;
        } catch (ClassNotFoundException e) {
            java.util.logging.Logger.getLogger(PREFIX)
                    .warning(String.format("SLF4J not found on the classpath.  Logging is disabled for the '%s' component", PREFIX));
            return false;
        }
    }
```

If you list the jars in `node_modules/.lib` you will probably see a slf4j jar there. Can you list the jars you see there, so I can try to prepare an reproducer to see how to configure the builtin logger config?

**Comment by Pakho** [comment] 2020-07-07 12:11
Hello,

Here are all the jar under .lib: 

asm-7.1.jar                
es4x-0.12.0.jar                 
mongodb-driver-async-3.10.1.jar     
netty-codec-socks-4.1.49.Final.jar    
profiler-20.1.0.jar            
vertx-unit-3.9.1.jar
asm-analysis-7.1.jar        
graal-sdk-20.1.0.jar            
mongodb-driver-core-3.10.1.jar      
netty-common-4.1.49.Final.jar         
regex-20.1.0.jar               
vertx-web-3.9.1.jar
asm-commons-7.1.jar         
icu4j-66.1.jar                  
netty-buffer-4.1.49.Final.jar       
netty-handler-4.1.49.Final.jar        
truffle-api-20.1.0.jar         
vertx-web-common-3.9.1.jar
asm-tree-7.1.jar            
jackson-annotations-2.10.2.jar  
netty-codec-4.1.49.Final.jar        
netty-handler-proxy-4.1.49.Final.jar  
vertx-auth-common-3.9.1.jar
asm-util-7.1.jar            
jackson-core-2.10.2.jar         
netty-codec-dns-4.1.49.Final.jar    
netty-resolver-4.1.49.Final.jar       
vertx-bridge-common-3.9.1.jar
bson-3.10.1.jar             
jackson-databind-2.10.2.jar     
netty-codec-http2-4.1.49.Final.jar  
netty-resolver-dns-4.1.49.Final.jar   
vertx-core-3.9.1.jar
chromeinspector-20.1.0.jar  
js-20.1.0.jar                   
netty-codec-http-4.1.49.Final.jar   
netty-transport-4.1.49.Final.jar      
vertx-mongo-client-3.9.1.jar

**Comment by pmlopes** [comment] 2020-07-07 12:58
@Pakho the issue is that `es4x` is setting the logging config and vertx-core only looks them on the classpath. I'll fix it on `es4x`, for now you can do the following:

create a `logging.properties` file or whatever name you prefer with:

```
handlers=java.util.logging.ConsoleHandler
java.util.logging.ConsoleHandler.formatter=io.reactiverse.es4x.jul.ES4XFormatter
java.util.logging.ConsoleHandler.level=FINEST

.level=WARNING
io.reactiverse.level=INFO
io.vertx.level=INFO
com.hazelcast.level=INFO
io.netty.util.internal.PlatformDependent.level=SEVERE
```

And then run the application as:

```
JAVA_OPTS="-Djava.util.logging.config.file=./logging.properties" npm start
```

In my case this stops showing the mongo logs. In es4x, i'll first verify if there is a logging properties in the current project dir, if yes, then use it otherwise fallback to the default.

**Comment by pmlopes** [comment] 2020-07-07 12:59
I'm closing this issue as invalid as it should be fixed on `es4x` and continue the work there.

**Closed by pmlopes** 2020-07-07 12:59 UTC
Labels: help wanted, wontfix
