### ISSUE TITLE
[3.6.2] MongoIterableStream execute the EndHandler even there is a bunch of data remaining in the pending queue

### ISSUE THREAD

**Issue by OSI-Califronia** [vert-x3/vertx-mongo-client#171] opened 2019-01-25 09:12 UTC
I changed the code inside to this so it works ...

#### MongoIterableStream ####
```java
 // Always called from a synchronized method or block
  private synchronized void doRead() {
    context.<List<JsonObject>>executeBlocking(fut -> {
      batchCursor.next((result, t) -> {
        if (t != null) {
          fut.fail(t);
        } else {
          fut.complete(result);
        }
      });
    }, true, ar -> {
      synchronized (this) {
        if (ar.succeeded()) {
          List<JsonObject> list = ar.result();
          if (list != null) {
            if (queue.write(list)) {
              doRead();
            }
          } else {
            // try to close stream
            if (!tryClose()) {
              queue.emptyHandler(h -> tryClose());
            }            
          }
        } else {
          close();
          handleException(ar.cause());
        }
      }
    });
  }

  private boolean tryClose() {
    if (queue.isEmpty()) {
      close();
      if (endHandler != null) {
        endHandler.handle(null);
      }
      return true;
    }
    return false;
  }
```

**Comment by karianna** [comment] 2019-01-25 20:33
Hi there,

I'm not sure if you're reporting a bug or supplying a patch?

**Comment by OSI-Califronia** [comment] 2019-01-28 07:42
I would say it's a bug, because the end handler you set on the readstream should only be invoked if all data of the stream has been consumed by the data handler first. Now its possible that this convetion could be broken. You can easily test this if you paus the readstream. But if you prefer a patch instead no problem.

**Comment by vietj** [comment] 2019-01-28 08:50
can you provide a reproducer @OSI-Califronia ?

**Comment by bsa01** [comment] 2019-04-01 15:45
I can reproduce with following code in MongoClientTest (3.6 branch)
`
 @Test
  public void findBatchResumePause() throws Exception {
    int docs= 111;
    testFindBatch((latch, stream) -> {
      List<String> foos = new ArrayList<>();
      CountDownLatch handlerCallsAfterPause = new CountDownLatch(docs);
      stream.exceptionHandler(this::fail).endHandler(v -> {
        latch.countDown();
        assertEquals(0, handlerCallsAfterPause.getCount());
      }).handler(result -> {
        foos.add(result.getString("foo"));
        stream.pause();
        vertx.setTimer(10, id -> {
          handlerCallsAfterPause.countDown();
          stream.resume();
        });
      });
      return foos;
    }, docs);
  }

  private void testFindBatch(BiFunction<CountDownLatch, ReadStream<JsonObject>, List<String>> checker, int numDocs) throws Exception {
    AtomicReference<ReadStream<JsonObject>> streamReference = new AtomicReference<>();

    String collection = randomCollection();
    CountDownLatch latch = new CountDownLatch(1);
    AtomicReference<List<String>> foos = new AtomicReference();
    mongoClient.createCollection(collection, onSuccess(res -> {
      insertDocs(mongoClient, collection, numDocs, onSuccess(res2 -> {
        FindOptions findOptions = new FindOptions().setSort(new JsonObject().put("foo", 1));
        ReadStream<JsonObject> stream = mongoClient.findBatchWithOptions(collection, new JsonObject(), findOptions);
        streamReference.set(stream);
        foos.set(checker.apply(latch, stream));
      }));
    }));
    awaitLatch(latch);
    assertEquals(numDocs, foos.get().size());
    assertEquals("bar0", foos.get().get(0));
    String bar = "bar";
    for(int i=0;i<String.valueOf(numDocs).length()-1;i++){
      bar = bar + "9";
    }
    assertEquals(bar, foos.get().get(numDocs - 1));
    // Make sure stream handlers can be set to null after closing
    streamReference.get().handler(null).exceptionHandler(null).endHandler(null);
  }
`
Test is failing with java.lang.AssertionError: expected:<0> but was:<11> .

Is this reproducer ok?

**Comment by Bjiji** [comment] 2019-11-21 13:15
For information and as stated above:

[230fe883d395aaa50f834433c9e016aba1f85877](https://github.com/OSI-Califronia/vertx-mongo-client/commit/230fe883d395aaa50f834433c9e016aba1f85877) seems to properly fix the issue for me.

I had the problem when using 3.8.0, but since I upgraded to 3.8.3 it disappeared.

**Closed** 2019-11-22 14:02 UTC
Labels: bug, to review
