### ISSUE TITLE
Stop throwing away useful results from Mongo

### ISSUE THREAD

**Issue by johnoliver** [vert-x3/vertx-mongo-client#40] opened 2015-09-04 16:48 UTC
A number of the operations such as update and replace throw away useful info by taking the UpdateResult (or whatever), throwing it away then returning null. Such as at:

https://github.com/vert-x3/vertx-mongo-client/blob/master/vertx-mongo-client/src/main/java/io/vertx/ext/mongo/impl/MongoClientImpl.java#L153

**Comment by karianna** [comment] 2015-09-04 19:35
I'd argue that's breaking the intent of wrapping that driver, so labelling as a bug.  PRs welcome!

**Comment by zdila** [comment] 2015-09-06 19:40
Isn't this a duplicate of #2 ?

**Comment by karianna** [comment] 2015-09-07 07:27
Very close to it, they could be merged probably. Doing so now...

**Closed by karianna** 2015-09-07 07:27 UTC
Labels: bug, duplicate, help wanted
